//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JazMax.AzureDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreUserInType
    {
        public int CoreUserInTypeId { get; set; }
        public int CoreUserId { get; set; }
        public int CoreUserTypeId { get; set; }
        public Nullable<bool> IsUserTypeActive { get; set; }
    }
}
