//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JazMax.AzureDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreBranch
    {
        public int BranchId { get; set; }
        public Nullable<int> CoreTeamLeaderId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string BranchName { get; set; }
        public string Phone { get; set; }
        public string EmailAddress { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string Suburb { get; set; }
    }
}
