//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JazMax.AzureDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreProvince
    {
        public int ProvinceId { get; set; }
        public string ProvinceName { get; set; }
        public Nullable<bool> IsAssigned { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
