//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JazMax.AzureDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreAgent
    {
        public int CoreAgentId { get; set; }
        public Nullable<int> CoreBranchId { get; set; }
        public Nullable<int> CoreTeamLeaderId { get; set; }
        public Nullable<int> CoreUserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
