//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JazMax.AzureDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JazMaxDBProdContext : DbContext
    {
        public JazMaxDBProdContext()
            : base("name=JazMaxDBProdContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CoreAgent> CoreAgents { get; set; }
        public virtual DbSet<CoreBranch> CoreBranches { get; set; }
        public virtual DbSet<CorePA> CorePAs { get; set; }
        public virtual DbSet<CoreProvince> CoreProvinces { get; set; }
        public virtual DbSet<CoreTeamLeader> CoreTeamLeaders { get; set; }
        public virtual DbSet<CoreUser> CoreUsers { get; set; }
        public virtual DbSet<CoreUserInType> CoreUserInTypes { get; set; }
        public virtual DbSet<CoreUserType> CoreUserTypes { get; set; }
        public virtual DbSet<vw_GetTeamLeadersInformation> vw_GetTeamLeadersInformation { get; set; }
        public virtual DbSet<vw_GetAgentsInformation> vw_GetAgentsInformation { get; set; }
        public virtual DbSet<MessengerCoreLog> MessengerCoreLogs { get; set; }
        public virtual DbSet<MessengerType> MessengerTypes { get; set; }
        public virtual DbSet<SystemSettingsData> SystemSettingsDatas { get; set; }
        public virtual DbSet<SystemErrorLog1> SystemErrorLog1 { get; set; }
    }
}
