//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JazMax.AzureDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemErrorLog1
    {
        public int SystemErrorLogId { get; set; }
        public string SystemErrorMessage { get; set; }
        public Nullable<System.DateTime> ErrorDateTime { get; set; }
        public Nullable<int> CoreUserId { get; set; }
    }
}
