//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JazMax.AzureDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSettingsData
    {
        public int SystemSettingsDataId { get; set; }
        public string SettingName { get; set; }
        public string SettingValueA { get; set; }
        public string SettingValueB { get; set; }
        public string SettingValueC { get; set; }
        public bool IsActive { get; set; }
    }
}
