//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JazMax.AzureDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetTeamLeadersInformation
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int CoreUserId { get; set; }
        public int CoreTeamLeaderId { get; set; }
        public string ProvinceName { get; set; }
        public string BranchName { get; set; }
        public int BranchId { get; set; }
        public string EmailAddress { get; set; }
    }
}
